### ISSUE TITLE
Flow: Watch action causes UI freeze on MCU

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#235] opened 2023-01-01 11:19 UTC
Watch action works fine in studio run/debug but not when running om MCU (RP2040+TFT)

Simple flow:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/8796121/210168350-4d478eb7-077e-415d-a478-77f34e613462.png">

I've setup a project to demo this:
https://github.com/fietser28/eez-flow-watchtest

The demo doesn't work, but if you remove the watch action it starts working. It looks like the initial display setup works (layout is shown) but all the text fields are NOT filled correctly.

**Comment by mvladic** [comment] 2023-01-01 13:19
Looks like `watchtest.eez-project` is not the latest version, can you push the latest version?

**Comment by mvladic** [comment] 2023-01-01 13:31
Are you sure that `ui_tick()` has been called periodically?

**Comment by fietser28** [comment] 2023-01-01 14:51
1. pushed latest version.
2. Yes it is, if I just remove the watch action the display updates nicely every second.

**Comment by mvladic** [comment] 2023-01-01 19:34
I can't reproduce this problem. What you mean by this: "... all the text fields are NOT filled correctly."?

**Comment by mvladic** [comment] 2023-01-01 19:36
I tested with web simulator repository (https://github.com/mvladic/lv_web_emscripten):

![watchtest](https://user-images.githubusercontent.com/449788/210182714-450656f6-9f4b-441c-9945-4fb9b3fd30f4.gif)

**Comment by mvladic** [comment] 2023-01-01 19:41
BTW Watch is not required to update label text as expressions is evaluated all the time in `ui_tick` function and label text is updated if text expression result is different then current label text.

**Comment by fietser28** [comment] 2023-01-01 21:00
I used this watch as a simple example (ran into it in more complex case and tried to narrow down the problem).

In studio the simulation it also works fine but on RP2040 it doesn't:

I'v added an extra project file to the GitHub (https://github.com/fietser28/eez-flow-watchtest)  with only the change that makes the UI freeze (probably on startup or first tick run?).

The watchtest project results in blinking and wd var label alternating true/false:
![IMG_0478](https://user-images.githubusercontent.com/8796121/210184245-4dd528e5-1fa3-4ccb-8008-128c69887259.jpg)

The watchtest-notworking project results in the picture below, without any UI updates. It looks like the UI task freezes.
![IMG_0475](https://user-images.githubusercontent.com/8796121/210184265-b9618075-31e0-43cd-8990-9d1b3353384b.jpg)

I've seen this earlier in other cases, always on RP2040 so it might also be a problem in the arduino framework/toolchain/freertos but given the fact is was always with the watch action it seems unlikely. In these cases removing the watch action and using variables directly solved the problem.

**Comment by mvladic** [comment] 2023-01-02 08:53
It also works on M5Stack, so it must be something with RP2040/Arduino. If you can debug then put the breakpoint at line 54 in eez/flow/hooks.cpp:

![image](https://user-images.githubusercontent.com/449788/210210380-c4e58beb-c377-44f2-8321-abf194675ac3.png)

and paste here the call stack.

**Comment by fietser28** [comment] 2023-01-02 20:38
I did some stepping/breakpoints in the debugger and it looks the ui_tick() is entered but never leaves:
![image](https://user-images.githubusercontent.com/8796121/210274077-c969e99a-8320-4647-9690-5576bb5d139b.png)

This looked especially strange to me because of the last if / break statement: This should timeout, but it doesn't. Further stepping revealed millis() is overloaded with lv_tick_get() in os.cpp:
![image](https://user-images.githubusercontent.com/8796121/210274311-dd5a73cf-e1f4-49e1-b32b-a004f15abbee.png)

This is not working because my display loop looks like:
![image](https://user-images.githubusercontent.com/8796121/210274589-cf90075f-b679-4bfe-a0c8-b6ff878a485c.png)
meaning lv_tick_inc never gets called when ui_tick is still processing.

In different code I placed  lv_tick_inc in a separate timer loop, but placed a mutex around all lv* and ui* calls because the rp2040 is multi-core and multi-thread. This didn't avoid the problem, so I updated the code in https://github.com/fietser28/eez-flow-watchtest without a mutex (lv_tick_inc is safe irt the other calls especially since lv_tick_get has a poor mans mutex test).

Conclusion: put lv_tick_inc in a separate task and it works. If this is intentional/by design we can close this problem.

**Comment by mvladic** [comment] 2023-01-02 23:37
What you mean by this "**If this is intentional/by design** we can close this problem."?

**Comment by mvladic** [comment] 2023-01-02 23:39
I wonder if maybe we should add another #ifdef for ARDUINO and in that case call `::millis()` which exists on that platform.

**Comment by prasimix** [comment] 2023-05-09 09:16
@fietser28 please let us know if we can close this ticket (it will be included in the next milestone)

**Comment by fietser28** [comment] 2023-05-10 15:06
Watch actions are now working fine in my case. It can be closed.

For the record: I currently use the following setup with Arduino + FreeRTOS:
```c
static void guiTimerFunction(TimerHandle_t tm)
{
  lv_tick_inc(MY_LV_TICK_TIME);
}

void gui_task_init(void)
{

  guiTimerHandle = xTimerCreate("", pdMS_TO_TICKS(MY_LV_TICK_TIME), pdTRUE, (void *) 0, guiTimerFunction);
  xTimerStart(guiTimerHandle, 10);

  xTaskCreate(guiTask, "", 4096 * 4, NULL, TASK_PRIORITY_UI, &guiTaskHandle);
};
```
And in the main guiTask the following l have:
```c
while (1)
  {
    lv_task_handler();
    ui_tick();
    vTaskDelay(pdMS_TO_TICKS(MY_LV_UPDATE_TIME));
  }
```

**Closed** 2023-05-10 15:19 UTC
Labels: EEZ Flow
