### ISSUE TITLE
Flow: Show/search SCPI documentation while editing SCPI component

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#287] opened 2023-09-11 06:48 UTC
In the instrument there is a nice SCPI documentation panel that dynamically searches the SCPI documentation if you type.

I would like to have the same panel present (by default at the bottom as an addition tab next to check/output/search/reference) that will search thru the documentation of the instrument I am editing the SCPI for.

It is slightly more complex than the script implementation:
- it needs to remove the <var> = before the scpi command and remove any variable substitions ({var}) in the present line
- determine which documentation to use. There are several options for this: 
  - query the instrument connected and see if an IEXT is present
  - let the user choose in the instrument properties which IEXT to use?
  - combination of both?

**Comment by mvladic** [comment] 2023-09-19 13:00
I have this idea to put command browser here:

![image](https://github.com/eez-open/studio/assets/449788/34d3b850-9b7a-439f-bee1-fff9eb373c6e)

![image](https://github.com/eez-open/studio/assets/449788/6c3989e0-b15e-4517-a3ff-a29108f56b6b)

This is work in progress.

**Comment by mvladic** [comment] 2023-09-22 12:49
This is implemented in the latest version.

**Comment by fietser28** [comment] 2023-10-28 11:54
It is working nice. I noticed a few things when using it. These are minor:

- [ ]  When I start editing an existing SCPI command (and the link button is checked) AND there is 1 SCPI command found the contents/help of this command is not shown. You have to click on it to show the manual info.

- [ ]  When multiple are found I would like to browse (using cursor key down/up?) to the right one instead of using the mouse to select one. Maybe I just don't know the right shortcut.

- [ ]  If the SCPI command (the command string itself not the arguments of the command) is composed using a variable the search will fail:

<img width="258" alt="image" src="https://github.com/eez-open/studio/assets/8796121/628be9fc-d76f-4dfb-a592-f0b3ce4cf917">

Removing the {} part results in:

<img width="258" alt="image" src="https://github.com/eez-open/studio/assets/8796121/66c4f28a-4915-41b8-b4dc-9177d1b58d34">

During the filtering I assume the part of the command with {} should probably be removed from the search as wel.

**Comment by mvladic** [comment] 2024-04-04 14:39
> When I start editing an existing SCPI command (and the link button is checked) AND there is 1 SCPI command found the contents/help of this command is not shown. You have to click on it to show the manual info.

Can't reproduce this problem.

> If the SCPI command (the command string itself not the arguments of the command) is composed using a variable the search will fail:

This should be fixed now.

**Comment by mvladic** [comment] 2024-04-05 12:29
> When multiple are found I would like to browse (using cursor key down/up?) to the right one instead of using the mouse to select one. Maybe I just don't know the right shortcut.

Implemented. F3 and Shift+F3 are keyboard shortcuts.

**Comment by fietser28** [comment] 2024-04-06 11:41
Thank you. I also can't reproduce the first item.

**Closed** 2024-04-08 17:09 UTC
Labels: enhancement, task, documentation, Instruments
